### ISSUE TITLE
add oid failded

### ISSUE THREAD

**Issue by AllBlue0** [pimvanpelt/vpp-snmp-agent#2]
[DEBUG   ]      agentx.agent - register       : Adding 1.3.6.1.2.1.2.2.1 to list
[DEBUG   ]      agentx.agent - register       : Adding 1.3.6.1.2.1.31.1.1.1 to list

**Comment by pimvanpelt** [comment]
This issue does not make clear what it is asking or suggesting. Please update it with a complete description of what you're trying to do, and attach a PR with code changes, if any, or close it.
