### ISSUE TITLE
Run - vpp-snmp-agent run with a error

### ISSUE THREAD

**Issue by DaxW** [pimvanpelt/vpp-snmp-agent#5]
Run Log:
[ERROR   ]      agentx.agent - setup          : Could not connect to VPPStats segment
[ERROR   ]      agentx.agent - run            : Setup failed - exiting
Run Cmd: 
vpp-snmp-agent -a /run/vpp/api.sock  -d

Which socket should I use to connect to VPPStats segment？

**Comment by DaxW** [comment]
![image](https://user-images.githubusercontent.com/69345905/209315668-005448ad-f096-4b35-9911-ad2c98186f70.png)

**Comment by pimvanpelt** [comment]
To answer the question, VPP Statistics are described here:
https://s3-docs.fd.io/vpp/22.10/developer/corefeatures/stats.html

Typically, /run/vpp/* is the directory where VPP opens its API and Stats socket.

I'm sorry but this repo does not accept github issues filed for user support, kindly stop using it as a helpdesk. See README.md for acceptable ways to get user support.
